# Generated by Django 5.0.4 on 2024-04-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=30)),
                ('pricep_number', models.CharField(max_length=30)),
                ('places', models.IntegerField()),
                ('names', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sostav_zakaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mass', models.FloatField()),
                ('count', models.IntegerField()),
                ('ed_izm', models.CharField(max_length=20)),
                ('place', models.IntegerField()),
                ('sht_place', models.IntegerField()),
            ],
        ),
    ]
