# Generated by Django 5.0.4 on 2024-05-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0003_alter_order_car_number_alter_order_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
