# Generated by Django 5.0.4 on 2024-05-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='names',
            field=models.IntegerField(verbose_name='Количество наименований'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Поступил', 'Поступил'), ('Принят', 'Принят'), ('В сборке', 'В сборке'), ('Ожидает отгрузки', 'Ожидает отгрузки'), ('Отгружается', 'Отгружается'), ('Отгружен', 'Отгружен'), ('Отменен', 'Отменен'), ('Изменен', 'Изменен'), ('Возникла проблема', 'Возникла проблема')], default='Поступил', max_length=30, verbose_name='Статус'),
        ),
    ]
