# Generated by Django 5.0.4 on 2024-05-16 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0007_alter_orderstatuschangehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='diplom.order', verbose_name='Номер заказа'),
        ),
    ]
